/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Laptop(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/laptop.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.pc} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.pc} position={[0, 0.021, 0.441]} rotation={[0.255, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/laptop.glb')
