/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { EffectComposer, SelectiveBloom } from '@react-three/postprocessing'
import { BlendFunction } from 'postprocessing'
import * as THREE from 'three'

export function Laptop(props) {
  const group = useRef()
  const screenRef = useRef()
  const matcapTexture = useTexture('/images/textures/mat1.png')
  const { nodes, materials } = useGLTF('/models/laptop.glb')

  const bodyMaterial = new THREE.MeshPhongMaterial({
    map: matcapTexture,
  })

  const frameMaterial = new THREE.MeshStandardMaterial({
    color: '#222',
    metalness: 0.6,
    roughness: 0.25,
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <EffectComposer>
        <SelectiveBloom
          selection={screenRef}
          intensity={1.5}
          luminanceThreshold={0.2}
          luminanceSmoothing={0.9}
          blendFunction={BlendFunction.ADD}
        />
      </EffectComposer>
      <group name="Scene">
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={bodyMaterial} />
        <mesh
          ref={screenRef}
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={frameMaterial}
          position={[0, 0.021, 0.441]}
          rotation={[0.255, 0, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/laptop.glb')
